### ISSUE TITLE
[BUG] main fails to compile on 3.9.0-SNAPSHOT — Jackson core/databind version skew

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/alerting#2227]
### What is the bug?
`opensearch-project/alerting` **main** (`7158bff7`, *Increment version to 3.9.0-SNAPSHOT (#2212)*) fails to compile. `./gradlew :alerting:compileKotlin` fails with Jackson classpath errors:

```
e: InputService.kt:248: Cannot access 'TreeNode' which is a supertype of 'JsonNode'.
   Check your module classpath for missing or conflicting dependencies.
e: PPLUtils.kt:124/177/212/…: Cannot access 'ObjectCodec' / 'Versioned' which is a supertype of 'ObjectMapper'
e: PPLUtils.kt: Cannot access 'TreeNode' which is a supertype of 'ArrayNode'/'ObjectNode'
e: TriggerService.kt:410: Cannot access 'TreeNode' which is a supertype of 'JsonNode'
> Task :alerting:compileKotlin FAILED
FAILURE: Build failed with an exception. … Compilation error.
```

### Diagnosis
`JsonNode`/`ObjectMapper`/`ArrayNode`/`ObjectNode` are **jackson-databind**; `TreeNode`/`ObjectCodec`/`Versioned` are their supertypes in **jackson-core**. `JsonNode extends TreeNode`, so this is a **jackson-databind newer than jackson-core** skew (the resolved `com.fasterxml.jackson.core:jackson-core` is missing the API the newer `jackson-databind` expects). The 3.9.0-SNAPSHOT bump (building against newer OpenSearch core) appears to have re-introduced the skew.

The existing resolutionStrategy from #2196 only forces the **Jackson 3** group:
```groovy
if (details.requested.group.startsWith('tools.jackson')) { details.useVersion versions.jackson3 }
```
It does not align the **`com.fasterxml.jackson` (Jackson 2)** `jackson-core`/`jackson-databind`/`jackson-annotations` artifacts that are actually clashing here.

### How can one reproduce the bug?
`git checkout main && ./gradlew :alerting:compileKotlin` (JDK 21). Also surfaces in `alerting-dashboards-plugin` Cypress CI, which runs `./gradlew :alerting:run` against alerting main and then times out because OpenSearch never starts.

### What is the expected behavior?
main compiles and `:alerting:run` starts OpenSearch.

### Proposed fix
Extend the `resolutionStrategy` to force `com.fasterxml.jackson.core:jackson-core`, `jackson-databind`, and `jackson-annotations` to a single consistent version aligned with OpenSearch core's `versions.jackson`. A fix PR will follow.

**Comment by DarshitChanpura** [comment]
Update: this **no longer reproduces**.

Building main (`7158bff7`) locally with a fresh resolution — `./gradlew :alerting:compileKotlin --refresh-dependencies --rerun-tasks` (JDK 21) — now **succeeds** (only benign warnings, no Jackson errors). On the current classpath, `com.fasterxml.jackson.core:jackson-core`/`jackson-databind` resolve to `2.22.1` alongside `tools.jackson` (Jackson 3) `3.2.1`, and compilation passes.

The earlier failure was a **transient skew in the moving OpenSearch 3.9.0-SNAPSHOT dependencies** during the Jackson 2→3 (`com.fasterxml` → `tools.jackson`) migration, which has since been re-published/corrected upstream. Closing as transient / not currently reproducible — please reopen if it recurs on a fresh build.

**Comment by DarshitChanpura** [comment]
Reopening — I closed this prematurely; it is **intermittent, not resolved**.

It **reproduced again in CI at 2026-09-10T22:49Z** (alerting-dashboards-plugin Cypress workflow, `./gradlew :alerting:run` against main `7158bff7`) with the identical errors:
```
InputService.kt:248 Cannot access 'TreeNode' which is a supertype of 'JsonNode'
PPLUtils.kt Cannot access 'ObjectCodec' / 'Versioned' which is a supertype of 'ObjectMapper'
```
A local fresh build (`--refresh-dependencies`) happened to **pass** ~an hour earlier, so the outcome depends on which `com.fasterxml.jackson` (2.x) vs `tools.jackson` (3.x) versions the moving OpenSearch 3.9.0-SNAPSHOT resolves at build time — i.e., the backend compile is **non-deterministic** during the Jackson 2→3 migration.

Suggested durable fix: in `alerting/build.gradle`, force a consistent, compatible Jackson set (align `com.fasterxml.jackson.core:jackson-core`/`jackson-databind`/`jackson-annotations`, and reconcile the `tools.jackson` 3.x coexistence) rather than relying on transitive snapshot resolution.
